services:
  postgresdb:
    image: postgres
    container_name: sampledb
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: sampledb
      POSTGRES_PASSWORD: sampledb
    ports:
      - "5432:5432"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d